### ISSUE TITLE
No "prime powers too large" message for 39304

### ISSUE THREAD

**Issue by gnufinder** [alex-konovalov/gnu#161]
I noticed that the grpconst-package accepts the input

```
39304 = 2^3 * 17^3
```

Why does GAP not reutrn 

```
sorry - prime powers in order are too large
fail
```

although the input contains a primepower larger than 1000 (namely 17^3 = 4913 ) ?

**Comment by olexandr-konovalov** [comment]
As explained in #63 (see the code excerpt in the very beginning of that issue), the condition that is checked for every p^n is `if (p^n <> 512 and p^n <= 1000) or n <= 3` so in this case `n<=3` and calculation continues. As reported in #142, gnu(39304)=245.
