### ISSUE TITLE
Gnu(18480)=5397

### ISSUE THREAD

**Issue by hulpke** [alex-konovalov/gnu#17]
To submit new values of Gnu(n) to the database, please provide the following details:
- GAP code used for the calculation
- The order of the group: n =18480
- The number of groups of order n: Gnu(n) = 5397
- Version of GAP: 4.9 development
- Versions of critical packages: GrpConst, Cubefree, etc.
- Brief description of the computer used for the calculation (operating system, processor, RAM): MacPro 2013
- Runtime required to calculate Gnu(n):5 hours
- [x] Confirm that the output `r` of `ConstructAllGroups` is a _list_ of groups: 
    `ForAll(r,IsGroup)` should return `true`: Yes.

**Comment by olexandr-konovalov** [comment]
@hulpke Thanks! This is verified on Linux server (AMD Opteron 6376 1400 MHz processor, 512 GB RAM) and can be added to the database:

GAP      4.8.3
GrpConst 2.5
Runtime: 36988323 ms (about 10 hours)
