### ISSUE TITLE
gnu(3600)=4484 duration : about 36 minutes

### ISSUE THREAD

**Issue by gnufinder** [alex-konovalov/gnu#20]

**Comment by olexandr-konovalov** [comment]
Validated on Azure cloud standard DS3 v2 instance (4 cores, 14 GB RAM)

gnu(3600) = 4484

GAP      4.8.3
GrpConst 2.5
CubeFree 1.15
SglPPow  1.1
Runtime: 1279164 ms
Isomorphic groups eliminated

**Comment by olexandr-konovalov** [comment]
Closed as a duplicate of #15.
