### ISSUE TITLE
gnu(4752)=2919 duration : about 11 minutes

### ISSUE THREAD

**Issue by gnufinder** [alex-konovalov/gnu#21]

**Comment by olexandr-konovalov** [comment]
Validated on Azure cloud standard DS3 v2 instance (4 cores, 14 GB RAM)

gnu(4752) = 2919

GAP      4.8.3
GrpConst 2.5
CubeFree 1.15
SglPPow  1.1
Runtime: 384564 ms
Isomorphic groups eliminated
