### ISSUE TITLE
Bulk submission

### ISSUE THREAD

**Issue by markuspf** [alex-konovalov/gnu#52]
I think this needs a better "bulk submission" policy. I could submit numbers where each group comes in one commit of a pull request for example, but making pull requests for each number I find seems a bit tedious.

**Comment by olexandr-konovalov** [comment]
I think that submitting a PR which contains multiple commits, one per each order, is a reasonable compromise. In this case the reviewer will create a checklist for each of the orders included in the PR and will merge the PR as soon as ALL orders will be validated. 

I would expect that in this case calculations for individual cases would not be too long, so it would be feasible to check all orders. There will be also ways to resolve situations if problems with some orders included in the PR will be discovered.

I will explain this in the README/CONTRIBUTING files. Also I am going to say there that one could easily submit a PR to add one line to `data/gnudata.g` via the GitHub interface.

**Comment by olexandr-konovalov** [comment]
See an example in https://github.com/alex-konovalov/gnu/pull/58 - pull request merging a collection of updates, strictly one per commit. As a side effect of that PR (actually, that increased the priority of that PR), new entries from the wishlist now will be more likely interleaved with existing ones, so there should be less merge conflicts. I am now ready to resolve conflicts in the currently open PRs and merge all what is by now validated, but not today.

**Comment by olexandr-konovalov** [comment]
Explained in README.md in https://github.com/alex-konovalov/gnu/commit/5f4400b4d54cac28c9d893ee9d234f23837eada2
