### ISSUE TITLE
gnu(9792)=73284

### ISSUE THREAD

**Issue by markuspf** [alex-konovalov/gnu#70]
`ConstructAllGroups` returns 7 pairs of groups it does not know how to split.

The construction took `96396.338` seconds.

**Comment by olexandr-konovalov** [comment]
I've started this with new GnuByConstructAllGroups from lib/grpconst.g

**Comment by olexandr-konovalov** [comment]
gnu(9792)=73284

GAP      4.8.3
GrpConst 2.5
Runtime of ConstructAllGroups: 57555876 ms
Returned a list of length 73274 containing 73264 groups and 10 sublists
Length of sublists : [ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 ]
Runtime to check non-isomorphism of groups in pairs: 145740616

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)

In case this value is new, add the next line to data/gnudata.g
GNU_SAVE( 9792, 73284, WITH_GC );

**Comment by olexandr-konovalov** [comment]
This is another case when the number of sublists differs, but the determined value of gnu(n) stays the same - marked this as a question for now, I'd like to understand deeper what's going on.

**Comment by olexandr-konovalov** [comment]
Another replication:

gnu(9792)=73284

GAP      4.8.4
GrpConst 2.5
Runtime of ConstructAllGroups: 58881992 ms (16.36 hrs)
Returned a list of length 73274 containing 73264 groups and 10 sublists
Length of sublists : [ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 ]
Runtime to check non-isomorphism of groups in pairs: 30233095 ms (8.4 hrs)

Replicated by @alex-konovalov on Ubuntu 16.04 on Azure cloud standard DS13 v2 instance (8 cores, 56 GB memory)
